SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABASE `db_camagru` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `db_camagru`;

CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	login VARCHAR(255) NOT NULL, 
	password VARCHAR(255) NOT NULL,
	groupe ENUM ('user', 'admin', 'other') NOT NULL DEFAULT 'user',
	email VARCHAR(255) NOT NULL,
	confirmation ENUM ('yes', 'no') NOT NULL DEFAULT 'no');

CREATE TABLE montages (
	id_montage INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	login VARCHAR(255) NOT NULL,
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE comments (
	id_comment INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_montage INT NOT NULL,
	auteur VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE likes (
	id_like INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_montage INT NOT NULL,
	auteur VARCHAR(255) NOT NULL,
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
